const elements = [
    {
        "type": "fixed_text",
        "label": "Testo fisso", 
        "icon": "<i class='fa fa-align-left'></i>", 
        "value": "",
        "preview": true,
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": "",
        "layout_alignment": "right"
    },
    {
        "type": "image",
        "label": "Immagine", 
        "icon": "<i class='fa fa-picture-o'></i>", 
        "path": "",
        "caption": "",
        "preview": true,
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": "",
        "layout_alignment": "left"
    },
    {
        "type": "answer_text_editor",
        "label": "Compilabile", 
        "icon": "<i class='fa fa-edit'></i>", 
        "question": "", 
        "tooltip": "",
        "answer": "",  
        "preview": true,
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "required": false,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": "",
        "layout_alignment": "right"
    },
    {
        "type": "data_sheet",
        "label": "Scheda tecnica", 
        "icon": "<i class='fa fa-list-alt'></i>", 
        "question": "", 
        "tooltip": "",
        "answer": "",  
        "preview": false,
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": "",
        "layout_alignment": "right",
        "data_sheet": "",
        "visibility_by_component": false,
        "components": []
    },
    {
        "type": "page_break",
        "label": "Salto pagina", 
        "icon": "<i class='fa fa-long-arrow-down'></i>", 
        "preview": false,
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": "",
        "layout_alignment": "right"
    },
    {
        "type": "dimensions",
        "label": "Misure", 
        "icon": "<i class='fa fa-superscript'></i>", 
        "answer": "",
        "preview": false,
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": "",
        "layout_alignment": "right"
    }
];