const elements = [
    {
        "type": "free_text",
        "label": "Testo libero", 
        "icon": "<i class='fa fa-edit'></i>", 
        "value": "",
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
    },
    {
        "type": "image",
        "label": "Immagine", 
        "icon": "<i class='fa fa-picture-o'></i>", 
        "path": "",
        "caption": "",
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
    },
    {
        "type": "standard_text",
        "label": "Testo standard", 
        "icon": "<i class='fa fa-align-left'></i>", 
        "name": "",
        "value": "",
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
    },
];