const questions = [
    {
        "id": "",
        "type": "short_answer",
        "label": "Risposta breve",
        "icon": "<i class='fa fa-pencil'></i>",
        "question": "", 
        "tooltip": "",
        "answer": "",  
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "required": false,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": ""
    },
    {
        "id": "",
        "type": "free_answer",
        "label": "Risposta aperta",
        "icon": "<i class='fa fa-edit'></i>",
        "question": "", 
        "tooltip": "",
        "answer": "",  
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "required": false,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": ""
    },
    {
        "id": "",
        "type": "yes_no",
        "label": "Si/No",
        "icon": "<i class='fa fa-thumbs-o-up'></i> <i class='fa fa-thumbs-o-down'></i>",
        "question": "", 
        "tooltip": "",
        "answer": "",  
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "required": false,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": ""
    },
    {
        "id": "",
        "type": "single_choice",
        "label": "Scelta singola",
        "icon": "<i class='fa fa-square-o'></i> <i class='fa fa-check-square-o'></i> <i class='fa fa-square-o'></i>",
        "question": "", 
        "tooltip": "",
        "view_mode": "list",
        "options": [],
        "answer": {
            "check": "",
            "extensions": []
        },  
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "required": false,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": ""
    },
    {
        "id": "",
        "type": "multiple_choice",
        "label": "Scelta multipla",
        "icon": "<i class='fa fa-square-o'></i> <i class='fa fa-check-square-o'></i> <i class='fa fa-check-square-o'></i>",
        "question": "", 
        "tooltip": "",
        "options": [],
        "scroll": false,
        "other": false,
        "other_answer_check": false,
        "other_answer": "",
        "answer": [], 
        "conditioned": false,
        "connected_to": "",
        "show_on": "", 
        "visible": true,
        "required": false,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": ""
    },
    {
        "id": "",
        "type": "date",
        "label": "Data",
        "icon": "<i class='fa fa-calendar'></i>",
        "question": "", 
        "tooltip": "",
        "answer": "",  
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "required": false,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": ""
    },
    {
        "id": "",
        "type": "number",
        "label": "Numero",
        "icon": "<i class='fa fa-sort-numeric-asc'></i>",
        "question": "", 
        "tooltip": "",
        "answer": "",  
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "required": false,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": ""
    },
    {
        "id": "",
        "type": "table",
        "label": "Tabella",
        "icon": "<i class='fa fa-table'></i>",
        "question": "", 
        "tooltip": "",
        "headers": [],
        "answer": [],  
        "conditioned": false,
        "connected_to": "",
        "show_on": "",
        "visible": true,
        "required": false,
        "show_in_table": false,
        "label_table": "",
        "show_in_export": false,
        "label_export": ""
    },
];